### PR TITLE
Fix the problems in Issue #8.

### PR DESCRIPTION
**Pull request by aperloff**
Fixes the problems in issue #8.

### CODE REVIEW

**Comment by aperloff** [comment]
@jmduarte @faroukmokhtar, please review.

**Comment by aperloff** [comment]
@jmduarte, I guess we don't have pyROOT anymore? The upper half of notebook 2 no longer works.

**Comment by jmduarte** [comment]
@aperloff yeah, we don't have pyROOT because it's pretty heavy to install ROOT with `conda`, it could be added though. I would maybe flag that notebook as "Optional" especially since we do it with `uproot` now anyway.

**Comment by farakiko** [comment]
> @jmduarte @faroukmokhtar, please review.

It's good to go. Thanks.

**Pull request merged**
